/**
 * Central source of truth for:
 *   - The ordered list of available commands (drives tab completion).
 *   - The COMPLETIONS map (tab-completes arguments per command).
 */

import { THEMES, FONTS } from "@/commands/theme-command";

// ─────────────────────────────────────────────────────────────────
// COMMAND LIST  (alphabetical order)
// ─────────────────────────────────────────────────────────────────

export const commands: string[] = [
  "about",
  "age",
  "audio",
  "calc",
  "clear",
  "color",
  "contact",
  "convert",
  "cowsay",
  "curl",
  "date",
  "decode",
  "echo",
  "email",
  "encode",
  "exit",
  "game",
  "github",
  "hash",
  "help",
  "history",
  "hostname",
  "ip",
  "joke",
  "man",
  "neofetch",
  "note",
  "projects",
  "quote",
  "repo",
  "resume",
  "rps",
  "snippet",
  "sudo",
  "theme",
  "time",
  "timer",
  "todo",
  "typeface",
  "uuid",
  "weather",
  "welcome",
  "whoami",
];

// ─────────────────────────────────────────────────────────────────
// COMPLETIONS MAP  (argument completion per command)
// ─────────────────────────────────────────────────────────────────

export const COMPLETIONS: Record<string, string[]> = {
  // Theming — derived from THEMES / FONTS objects automatically
  theme: Object.keys(THEMES),
  typeface: Object.keys(FONTS),

  // Audio
  audio: ["on", "off", "volume", "--help", "help", "-h"],

  // Fun & Games
  rps: ["rock", "paper", "scissors", "--help", "help", "-h"],
  game: ["stats", "reset", "help", "--help", "-h"],

  // Network
  curl: [
    "--help",
    "-h",
    "-v",
    "--verbose",
    "-I",
    "--head",
    "-s",
    "--silent",
    "-X",
    "--request",
    "-H",
    "--header",
    "-d",
    "--data",
    "--data-raw",
    "--data-binary",
    "-u",
    "--user",
    "-L",
    "--location",
    "-o",
    "--output",
    "-w",
    "--write-out",
    "help",
  ],

  // Encoding & hashing
  encode: ["base64", "url", "hex", "--help", "help", "-h"],
  decode: ["base64", "url", "hex", "--help", "help", "-h"],
  hash: ["sha256", "sha512", "sha384", "sha1", "--help", "help", "-h"],

  // Utilities — subcommand-based
  note: [
    "add",
    "rm",
    "remove",
    "delete",
    "edit",
    "update",
    "clear",
    "list",
    "help",
    "--help",
    "-h",
  ],
  todo: [
    "add",
    "done",
    "undone",
    "rm",
    "remove",
    "delete",
    "clear",
    "list",
    "help",
    "--help",
    "-h",
  ],
  snippet: ["add", "show", "rm", "remove", "delete", "clear", "list", "help", "--help", "-h"],
  uuid: ["v1", "v4", "validate", "help", "--help", "-h"],
  convert: ["list", "--json", "-j", "help", "--help", "-h"],

  // Color converter — accepts color names
  color: [
    "red",
    "green",
    "blue",
    "white",
    "black",
    "gray",
    "grey",
    "yellow",
    "cyan",
    "magenta",
    "orange",
    "purple",
    "pink",
    "brown",
    "lime",
    "navy",
    "teal",
    "silver",
    "gold",
    "coral",
    "salmon",
    "turquoise",
    "violet",
    "indigo",
    "crimson",
    "lavender",
    "mint",
    "tomato",
    "orchid",
    "khaki",
    "--help",
    "help",
    "-h",
  ],

  // man pages — completes to all command names that have man entries
  man: [
    "about",
    "age",
    "audio",
    "calc",
    "clear",
    "color",
    "contact",
    "convert",
    "cowsay",
    "curl",
    "date",
    "decode",
    "echo",
    "email",
    "encode",
    "exit",
    "game",
    "github",
    "hash",
    "help",
    "history",
    "hostname",
    "ip",
    "joke",
    "man",
    "neofetch",
    "note",
    "projects",
    "quote",
    "repo",
    "resume",
    "rps",
    "snippet",
    "sudo",
    "theme",
    "time",
    "timer",
    "todo",
    "typeface",
    "uuid",
    "weather",
    "welcome",
    "whoami",
    "--help",
    "help",
    "-h",
  ],

  // Simple commands — always accept --help, -h and help
  about: ["--help", "help", "-h"],
  age: ["--help", "help", "-h"],
  calc: ["--help", "help", "-h"],
  contact: ["--help", "help", "-h"],
  cowsay: ["--help", "help", "-h"],
  date: ["--help", "help", "-h"],
  echo: ["--help", "help", "-h"],
  email: ["--help", "help", "-h"],
  exit: ["--help", "help", "-h"],
  github: ["--json", "-j", "--help", "help", "-h"],
  history: ["--help", "help", "-h"],
  hostname: ["--help", "help", "-h"],
  ip: ["--json", "-j", "--help", "help", "-h"],
  joke: ["--json", "-j", "--help", "help", "-h"],
  neofetch: ["--help", "help", "-h"],
  projects: ["--help", "help", "-h"],
  quote: ["--json", "-j", "--help", "help", "-h"],
  repo: ["--help", "help", "-h"],
  resume: ["--help", "help", "-h"],
  sudo: ["--help", "help", "-h"],
  time: ["--help", "help", "-h"],
  timer: ["--help", "help", "-h"],
  weather: ["--help", "help", "-h"],
  welcome: ["--help", "help", "-h"],
  whoami: ["--help", "help", "-h"],
};
